name: Firebase Cloud Functions
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install JS dependencies
        run: yarn install

      - name: Test
        run: yarn test

      - name: Deploy Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
